### ISSUE TITLE
How to use TracerAwareInstrumentation

### ISSUE THREAD

**Issue by AriPaaWun** [elastic/apm-agent-java-plugin-example#14]
Hi,

I'm trying to instrument HTTP Kit client so that it would include headers needed for distributed tracing.

I figured that best way to do this would be to instrument [HttpClient#exec](https://github.com/http-kit/http-kit/blob/master/src/java/org/httpkit/client/HttpClient.java#L311). My idea was that I could add the header in `RequestConfig.headers` Map with onMethodEnter on `exec`.

I planned on using TracerAwareInstrumentation and added elastic-apm-agent as dependency with provided scope, but my IDE doesn't seem to find bci package for some reason.

Anyway, is the approach possible and correct for HTTP Kit or is there a better way?

**Comment by AriPaaWun** [comment]
I was able to get the bci package loaded. I guess proper dependency refresh helped. When using the SDK, I guess we are not supposed to use the agent or tracer or other such "inner" libraries in a plugin.

I also noticed that RequestConfig is quite (package) private and as such doesn't easily give anything to get or set. I could probably use byte code manipulation to achieve my goal, but that doesn't really seem like the proper way.

As such, this is all too complicated and taking more time than I'm willing to spend on this at the moment.

**Comment by jackshirazi** [comment]
Hi, the community plugin is targeted at using the public APIs - either the [Elastic APM Java agent](https://www.elastic.co/guide/en/apm/agent/java/current/public-api.html) or the [OpenTelemetry](https://opentelemetry.io/docs/instrumentation/java/manual/) one - not the internals of the agent. For example [OTel context propagation](https://opentelemetry.io/docs/instrumentation/java/manual/#context-propagation) would be the recommended option to set distributed tracing headers

**Comment by AriPaaWun** [comment]
Ok, thank you for the clarification.
